databases:
  - name: brtecnologia-db
    databaseName: brtecnologia
    user: brtecnologia
    plan: free
    region: oregon

services:
  - type: web
    name: brtecnologia-catalog
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_NAME
        value: "B&R Tecnología"
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_KEY
        value: "base64:uA3aKZpEtiNi4HvEwwyHcTyDJvZLTUYtFzE/XtqJHXA="
      - key: APP_URL
        value: "https://brtecnologia-catalog1.onrender.com"
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: pgsql
      - key: DATABASE_URL
        fromDatabase:
          name: brtecnologia-db
          property: connectionString
      - key: SESSION_DRIVER
        value: cookie
      - key: SESSION_SECURE_COOKIE
        value: "true"
      - key: CACHE_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync
      # Resend API para envío de correos (HTTP, no bloqueado por Render)
      - key: RESEND_API_KEY
        value: "re_6WW2USse_64zokCHrmMW8d8i2bsbRzXwj"
      - key: MAIL_FROM_ADDRESS
        value: "onboarding@resend.dev"
      - key: MAIL_FROM_NAME
        value: "B&R Tecnología"
